# -*- coding: utf-8 -*-
"""Object detection2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K4y-bQMqRlw3qJE48LrHTkF6X5jErS4Y
"""

# Commented out IPython magic to ensure Python compatibility.
import os
from os.path import exists, join, basename, splitext
import time

#Connect to drive
from google.colab import drive
drive.mount('/content/drive')

#Download weight files for object detection (yolo9000)
# %cd /content
if not exists('/content/yolo9000.weights'):
  !wget http://pjreddie.com/media/files/yolo9000.weights

#Download source from github
# %cd /content/
if not exists('/content/darknet' or '/content/darknet-master'):
#   %cd /content/
  !git clone --recursive https://github.com/thodorostsao/4-leg-robot-neural-network.git
  !unzip /content/4-leg-robot-neural-network/darknet-master.zip
#   %cd darknet-master
  !make
  os.rename('/content/darknet-master', '/content/darknet')

##
i=0


while True:
  if i!=0:
    !./darknet detector test /content/darknet/cfg/combine9k.data /content/darknet/cfg/yolo9000.cfg /content/yolo9000.weights -ext_output -dont_show -out /content/result.json < /content/listimages.txt
    #Code for reading result.json, then checking if contains fire, smoke bottle bear tigger eg... +anazitish gia spania eidi 
    time.sleep(10) #Sleep is at the start of loop, because to be complete written the paths of images on the file
    break
  mylist = ""    #listimages.txt, must end the loop and go from the start
  with open("/content/listimages.txt", "w", encoding="utf-8") as file:
      for eachfile in os.listdir("/content/drive/My Drive/"):
          if eachfile.endswith(".png"): #grabing only files that ends on jpg
            mylist += "/content/drive/My Drive/" + eachfile + "\n"
      file.write(mylist)
      print("Writed!")
      i +=1
#       %cd /content/darknet/